//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ludo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LudoBoardTable
    {
        public bool IsActive { get; set; }
    
        public virtual PieceTable PieceTable { get; set; }
        public virtual SquareTable SquareTable { get; set; }
        public virtual NestTable NestTable { get; set; }
        public virtual PlayerTable PlayerTable { get; set; }
    }
}
